#!/bin/bash

result=""
for item in *; do
    if [ -d "$item" ]; then
        result+="$item/, "
    else
        result+="$item, "
    fi
done

result=$(echo "$result" | sed 's/, $/\n/')
echo -e "$result"
